FROM redis:latest

# If you want to use your own redis.conf
#COPY redis.conf /usr/local/etc/redis/redis.conf
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

CMD ["redis-server"]

EXPOSE 6379
